spring:
  datasource:
    url: jdbc:h2:file:./movies

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true

  main:
    allow-circular-references: true

server:
  port: 8084

logging:
  file:
    name: application.log
  level:
    root: INFO
    ru.nikitinsky.Security2DbThymeleaf: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics